<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE  mundo [
	<!ELEMENT capital (#PCDATA)>
	<!ELEMENT nombrepais (#PCDATA)>
	<!ELEMENT nombrecontinente (#PCDATA)>
	<!ELEMENT pais (nombrepais, capital)>
	<!ELEMENT continente (nombrecontinente, pais+)>
	<!ELEMENT mundo (continente+)>
	<!ATTLIST correo xmlns:xsi CDATA #IMPLIED
					 xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
]>

<mundo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="02.xsd">
	<continente>
		<nombrecontinente>Europa</nombrecontinente>
		<pais>
			<nombrepais>Alemania</nombrepais>
			<capital>Berlin</capital>
		</pais>
	</continente>
	<continente>
		<nombrecontinente>America</nombrecontinente>
		<pais>
			<nombrepais>Argentina</nombrepais> 
			<capital>Buenos Aires</capital>
		</pais>
		<pais>
			<nombrepais>Bahamas</nombrepais>
			<capital>Nassau</capital>
		</pais>
	</continente>
	<continente>
		<nombrecontinente>Asia</nombrecontinente>
		<pais>
			<nombrepais>Afganistan</nombrepais>
			<capital>Kabul</capital>
		</pais>
		<pais>
			<nombrepais>Arabia Saudita</nombrepais>
			<capital>Riad</capital>
		</pais>
	</continente>
</mundo>