=== NachoPLSauces/Proyecto1920_LMGSI_NPL/1920_LMGSI_NPL/XML/03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
<xs:element name="hechoshistoricos">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="hecho" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="descripcion"/>
						<xs:element name="fecha" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="dia" type="xs:string"/>
									<xs:element name="mes" type="xs:string"/>
									<xs:element name="anyo" type="xs:string"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence> 
				</xs:complexType> 
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== NachoPLSauces/Proyecto1920_LMGSI_NPL/1920_LMGSI_NPL/XML/03.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE  hechoshistoricos [
	<!ELEMENT descripcion (#PCDATA)>
	<!ELEMENT dia (#PCDATA)>
	<!ELEMENT mes (#PCDATA)>
	<!ELEMENT año (#PCDATA)>
	<!ELEMENT fecha (dia, mes, año)>
	<!ELEMENT hecho (descripcion, fecha)>
	<!ELEMENT hechoshistoricos (hecho+)>
	<!ATTLIST correo xmlns:xsi CDATA #IMPLIED
					 xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
]>

<hechoshistoricos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="03.xsd">
	<hecho>
		<descripcion>Se funda Youtube</descripcion>
		<fecha>
			<dia>15</dia>
			<mes>2</mes>
			<año>2005</año>
		</fecha>
	</hecho>
	<hecho>
		<descripcion>Se funda Google</descripcion>
		<fecha>
			<dia>4</dia>
			<mes>9</mes>
			<año>1998</año>
		</fecha>
	</hecho>
	<hecho>
		<descripcion>Se funda Facebook</descripcion>
		<fecha>
			<dia>4</dia>
			<mes>2</mes>
			<año>2004</año>
		</fecha>
	</hecho>
</hechoshistoricos>
