=== NachoPLSauces/Proyecto1920_LMGSI_NPL/1920_LMGSI_NPL/XML/04.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">

<xs:element name="correo">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="remitente"/>
			<xs:element name="destinatarios">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="correousuario" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="asunto"/>
			<xs:element name="mensaje"/>
			<xs:element name="adjuntos">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="imagen" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="type">
											<xs:simpleType>
												<restriction base="xs:string">
													<!-- <xs:enumeration value="png"/> -->
													<!-- <xs:enumeration value="jpg"/> -->
													<xs:pattern value="png|jpg"/>
												</restriction>
											</xs:simpleType>
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="fecha" type="xs:date"/>
	</xs:complexType>
</xs:element>
</xs:schema>

=== NachoPLSauces/Proyecto1920_LMGSI_NPL/1920_LMGSI_NPL/XML/04.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE correo [
	<!ELEMENT remitente (#PCDATA)>
	<!ELEMENT correousuario (#PCDATA)>	
	<!ELEMENT asunto (#PCDATA)>
	<!ELEMENT mensaje (#PCDATA)>
	<!ELEMENT tipo (#PCDATA)>
	<!ELEMENT destinatarios (correousuario+)>
	<!ELEMENT imagen (#PCDATA)>
	<!ELEMENT adjuntos (imagen+)>
	<!ELEMENT correo (remitente, destinatarios, asunto?, mensaje, adjuntos?)>
	<!ATTLIST correo xmlns:xsi CDATA #IMPLIED
					 xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
	<!ATTLIST correo fecha CDATA #IMPLIED>
	<!ATTLIST imagen type (png|jpg) #REQUIRED>
]>

<correo fecha="14/01/2020" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="04.xsd">
	<remitente>marodriguezn@educa.jcyl.es</remitente>
	<destinatarios>
		<correousuario>eduardo@educa.jcyl.es</correousuario>
		<correousuario>maria@educa.jcyl.es</correousuario>
	</destinatarios>
	<asunto>Fiesta de fin de curso</asunto>
	<mensaje>A las 20:00 en...</mensaje>
	<adjuntos>
		<imagen type="png">foto1.png</imagen>
		<imagen type="png">foto2.png</imagen>
	</adjuntos>
</correo>
