<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE  hechoshistoricos [
	<!ELEMENT descripcion (#PCDATA)>
	<!ELEMENT fecha (#PCDATA)>
	<!ELEMENT hecho (descripcion, fecha)>
	<!ELEMENT hechoshistoricos (hecho+)>
	<!ATTLIST fecha dia CDATA #REQUIRED>
	<!ATTLIST fecha mes CDATA #REQUIRED>
	<!ATTLIST fecha anyo CDATA #REQUIRED>
]>

<hechoshistoricos>
	<hecho>
		<descripcion>Se funda Youtube</descripcion>
		<fecha dia="15" mes="02" anyo="2005"/>
	</hecho>
	<hecho>
		<descripcion>Se funda Google</descripcion>
		<fecha dia="04" mes="09" anyo="1998"/>
	</hecho>
	<hecho>
		<descripcion>Se funda Facebook</descripcion>
		<fecha dia="04" mes="02" anyo="2004"/>
	</hecho>
</hechoshistoricos>